#!/usr/bin/env python3
"""Tests for the alignment contract: PLY reading, frame maths, manifest validation.

These cover the pure logic, so the expensive measurement run does not have to be
repeated to check that the contract still holds its own invariants. The specific
bugs these guard against are the ones that shipped:

* the up axis read from the wrong basis column, which passed because the wrong
  column happened to look plausible
* a mirrored (det < 0) basis, which parses and renders
* the centroid translation applied twice, which shifts the room silently
* trusting the normal's *sign* to pick floor vs ceiling, which finds the same
  sheet twice and reports a zero-thickness room

Run with: python3 -m pytest scripts/splat_pipeline/tests/test_splat_frame.py -v
"""

import struct
import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import colmap_model
import frame_axes
import splat_geometry
import splat_ply
from splat_frame import (
    SCHEMA_VERSION,
    CameraPath,
    ContractError,
    FrameContract,
    PlyToWorld,
    ScaleReference,
)

# ---------------------------------------------------------------------------
# PLY reading
# ---------------------------------------------------------------------------

PROPERTIES = [
    "x", "y", "z",
    "scale_0", "scale_1", "scale_2",
    "opacity",
    "rot_0", "rot_1", "rot_2", "rot_3",
]


def write_ply(path: Path, rows: list[dict]) -> None:
    """Write a minimal binary_little_endian 3DGS PLY with the given rows."""
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment Generated by test\n"
        "comment Vertical Axis: z\n"
        f"element vertex {len(rows)}\n"
        + "".join(f"property float {name}\n" for name in PROPERTIES)
        + "end_header\n"
    )
    body = b"".join(
        struct.pack("<%df" % len(PROPERTIES), *[float(row.get(name, 0.0)) for name in PROPERTIES])
        for row in rows
    )
    path.write_bytes(header.encode("ascii") + body)


def make_row(x=0.0, y=0.0, z=0.0, opacity=10.0):
    return {"x": x, "y": y, "z": z, "opacity": opacity, "rot_0": 1.0, "scale_0": -6.0}


class TestSplatPly:
    def test_reads_positions_and_count(self, tmp_path):
        ply = tmp_path / "a.ply"
        write_ply(ply, [make_row(1.0, 2.0, 3.0), make_row(-1.0, -2.0, -3.0)])
        header = splat_ply.parse_header(ply)
        assert header.vertex_count == 2
        assert header.properties == tuple(PROPERTIES)
        assert np.allclose(splat_ply.read_positions(ply), [[1, 2, 3], [-1, -2, -3]])

    def test_alphas_are_sigmoid_of_opacity(self, tmp_path):
        ply = tmp_path / "b.ply"
        write_ply(ply, [make_row(opacity=0.0), make_row(opacity=1000.0)])
        alphas = splat_ply.read_alphas(ply)
        assert alphas[0] == pytest.approx(0.5, abs=1e-6)
        assert alphas[1] == pytest.approx(1.0, abs=1e-6)

    def test_header_comments_are_exposed_as_provenance(self, tmp_path):
        ply = tmp_path / "c.ply"
        write_ply(ply, [make_row()])
        comments = splat_ply.header_comments(ply)
        assert comments["generated"] == "by test"
        # The exporter's claim about the frame is recorded, not trusted.
        assert comments["vertical"] == "Axis: z"

    def test_rejects_non_binary_ply(self, tmp_path):
        ply = tmp_path / "ascii.ply"
        ply.write_text("ply\nformat ascii 1.0\nend_header\n")
        with pytest.raises(splat_ply.PlyFormatError):
            splat_ply.parse_header(ply)

    def test_rejects_missing_position_properties(self, tmp_path):
        ply = tmp_path / "bad.ply"
        ply.write_bytes(
            b"ply\nformat binary_little_endian 1.0\nelement vertex 1\n"
            b"property float u\nproperty float v\nend_header\n" + b"\x00" * 8
        )
        with pytest.raises(splat_ply.PlyFormatError):
            splat_ply.parse_header(ply)


# ---------------------------------------------------------------------------
# frame_axes: the rotation contract
# ---------------------------------------------------------------------------

class TestWorldBasis:
    def test_z_up_maps_onto_godot_up(self):
        basis = frame_axes.world_basis_for(up_axis=2, width_axis=1, up_sign=1)
        # frame +z (up) must land on Godot +y
        assert np.allclose(basis @ np.array([0.0, 0.0, 1.0]), [0.0, 1.0, 0.0])

    def test_negative_up_sign_flips_the_vertical(self):
        basis = frame_axes.world_basis_for(up_axis=2, width_axis=1, up_sign=-1)
        assert np.allclose(basis @ np.array([0.0, 0.0, 1.0]), [0.0, -1.0, 0.0])

    @pytest.mark.parametrize("up_axis", [0, 1, 2])
    @pytest.mark.parametrize("width_axis", [0, 1, 2])
    def test_always_a_proper_rotation(self, up_axis, width_axis):
        if up_axis == width_axis:
            with pytest.raises(ValueError):
                frame_axes.world_basis_for(up_axis=up_axis, width_axis=width_axis)
            return
        basis = frame_axes.world_basis_for(up_axis=up_axis, width_axis=width_axis)
        assert float(np.linalg.det(basis)) == pytest.approx(1.0)
        assert np.allclose(basis @ basis.T, np.eye(3))

    def test_every_frame_up_axis_lands_on_godot_up(self):
        for up_axis in (0, 1, 2):
            for width_axis in (0, 1, 2):
                if up_axis == width_axis:
                    continue
                basis = frame_axes.world_basis_for(up_axis, width_axis, 1)
                axis = np.eye(3)[up_axis]
                assert np.allclose(basis @ axis, [0.0, 1.0, 0.0])

    def test_rejects_up_sign_zero(self):
        with pytest.raises(ValueError):
            frame_axes.world_basis_for(up_axis=2, width_axis=1, up_sign=0)

    def test_remaining_axis_is_the_spare_one(self):
        assert frame_axes.remaining_axis(2, 1) == 0
        assert frame_axes.remaining_axis(0, 2) == 1

    def test_axis_index_round_trips(self):
        for index, name in enumerate(frame_axes.AXIS_NAMES):
            assert frame_axes.axis_index(name) == index
        with pytest.raises(ValueError):
            frame_axes.axis_index("w")


# ---------------------------------------------------------------------------
# PlyToWorld
# ---------------------------------------------------------------------------

# The default reference: 0.48 reconstruction units == 2.4 m, so metres_per_unit
# must be 5.0 for the contract to validate.
REFERENCE_RAW_UNITS = 0.48
REFERENCE_TARGET_METRES = 2.4
EXPECTED_METRES_PER_UNIT = 5.0


def make_mapping(**overrides) -> PlyToWorld:
    defaults = {
        "basis_columns": ((0.0, 0.0, 1.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)),
        "metres_per_unit": EXPECTED_METRES_PER_UNIT,
        "origin_ply_units": (0.0, 0.0, 0.0),
        "frame_name": "test",
        "up_axis": "z",
        "up_sign": 1,
        "handedness": "right",
    }
    defaults.update(overrides)
    return PlyToWorld(**defaults)


class TestPlyToWorld:
    def test_default_scale_matches_its_reference(self):
        assert make_mapping().metres_per_unit == pytest.approx(
            REFERENCE_TARGET_METRES / REFERENCE_RAW_UNITS
        )

    def test_maps_up_axis_to_godot_up(self):
        mapping = make_mapping()
        assert np.allclose(mapping.frame_up_in_world(), [0.0, 1.0, 0.0])

    def test_world_point_applies_scale_and_centroid(self):
        mapping = make_mapping(metres_per_unit=2.0, origin_ply_units=(1.0, 0.0, 0.0))
        # The builder's centroid is already subtracted at import, so a point at the
        # raw centroid maps to the world origin.
        assert np.allclose(mapping.world_point((1.0, 0.0, 0.0)), [0.0, 0.0, 0.0], atol=1e-9)

    def test_world_vector_ignores_translation(self):
        mapping = make_mapping(origin_ply_units=(5.0, 5.0, 5.0))
        vector = mapping.world_vector((1.0, 0.0, 0.0))
        # frame +x -> Godot +z, scaled by metres_per_unit; the centroid plays no part
        assert np.allclose(vector, [0.0, 0.0, EXPECTED_METRES_PER_UNIT])

    def test_node_transform_has_zero_translation(self):
        mapping = make_mapping(origin_ply_units=(1.0, 2.0, 3.0))
        node = mapping.node_transform_matrix()
        # The builder already subtracted the centroid, so reapplying it would
        # double-subtract and shift the room. This is the guard for that.
        assert np.allclose(node[:, 3], 0.0)
        assert np.allclose(node[:, :3], mapping.linear_matrix())
        assert not np.allclose(mapping.matrix()[:, 3], 0.0)

    def test_rejects_a_mirrored_basis(self):
        mapping = make_mapping(
            basis_columns=((0.0, 0.0, 1.0), (1.0, 0.0, 0.0), (0.0, -1.0, 0.0))
        )
        with pytest.raises(ContractError, match="proper rotation"):
            mapping.rotation()

    def test_is_proper_rotation_detects_a_mirror(self):
        assert make_mapping().is_proper_rotation()
        # A mirrored basis has determinant -1; it parses and renders, so nothing
        # short of an explicit check will catch it.
        assert not make_mapping(
            basis_columns=((0.0, 0.0, 1.0), (1.0, 0.0, 0.0), (0.0, -1.0, 0.0))
        ).is_proper_rotation()

    def test_rejects_wrong_length_input(self):
        with pytest.raises(ContractError):
            make_mapping().world_point((1.0, 2.0))

    def test_rejects_left_handed_source_frame(self):
        contract = make_contract(
            ply_to_world=make_mapping(handedness="left"),
        )
        with pytest.raises(ContractError, match="right-handed"):
            contract.validate()


# ---------------------------------------------------------------------------
# ScaleReference
# ---------------------------------------------------------------------------

class TestScaleReference:
    def test_tolerance_grows_with_measured_spread(self):
        # 1% spread stays under the 10% floor; 10% spread sits on it; 30% is above.
        tight = ScaleReference("chosen", "h", 1.0, 0.01, 10, 2.4, "")
        floored = ScaleReference("chosen", "h", 1.0, 0.05, 10, 2.4, "")
        loose = ScaleReference("chosen", "h", 1.0, 0.30, 10, 2.4, "")
        assert floored.tolerance_metres == pytest.approx(tight.tolerance_metres)
        assert loose.tolerance_metres > floored.tolerance_metres

    def test_tolerance_tracks_the_raw_measurement(self):
        # The same fractional spread in a smaller measurement gives a smaller
        # tolerance, which is what makes the value meaningful rather than arbitrary.
        small = ScaleReference("chosen", "h", 0.5, 0.05, 10, 2.4, "")
        large = ScaleReference("chosen", "h", 2.0, 0.20, 10, 2.4, "")
        assert small.tolerance_metres == pytest.approx(large.tolerance_metres)

    def test_tolerance_is_floored_at_ten_percent(self):
        # A suspiciously perfect reconstruction must not demand an impossible
        # tolerance.
        reference = ScaleReference("chosen", "h", 1.0, 0.0, 10, 2.4, "")
        assert reference.tolerance_metres == pytest.approx(0.24)

    def test_rejects_zero_raw_units(self):
        # Zero raw units means a division by zero in the tolerance formula; the
        # property is read to force it rather than merely constructing the record.
        reference = ScaleReference("chosen", "h", 0.0, 0.01, 10, 2.4, "")
        with pytest.raises(ContractError):
            _ = reference.tolerance_metres


# ---------------------------------------------------------------------------
# FrameContract validation
# ---------------------------------------------------------------------------

def make_contract(**overrides) -> FrameContract:
    mapping = make_mapping(metres_per_unit=EXPECTED_METRES_PER_UNIT)
    reference = ScaleReference(
        kind="chosen",
        quantity="floor_to_ceiling_clear_height",
        raw_units=REFERENCE_RAW_UNITS,
        raw_units_spread=0.01,
        raw_units_spread_samples=12,
        target_metres=REFERENCE_TARGET_METRES,
        reason="test",
    )
    from splat_frame import ColliderBox, SplatBounds

    bounds = SplatBounds(
        observed_min=(-2.4, -1.2, -2.4),
        observed_max=(2.4, 1.2, 2.4),
        core_min=(-3.0, -2.0, -3.0),
        core_max=(3.0, 2.0, 3.0),
        full_min=(-10.0, -10.0, -10.0),
        full_max=(10.0, 10.0, 10.0),
        splat_count=1000,
    )
    # A camera path inside the room at a walking eye height. The mean sits 0.7 m
    # above the -1.2 m floor, inside the 0.4..2.2 m sanity band, and the whole
    # path stays well clear of the room's -1.2..1.2 m vertical span.
    cameras = CameraPath(
        count=192,
        world_min=(-1.0, -0.5, -1.0),
        world_max=(1.0, 0.5, 1.0),
        height_min_m=-0.5,
        height_mean_m=-0.5,
        height_max_m=0.5,
        source="test cameras",
    )
    defaults = {
        "schema_version": SCHEMA_VERSION,
        "scene_id": "test",
        "ply_to_world": mapping,
        "scale_reference": reference,
        "automatic_transforms": (),
        "landmarks": {
            "floor": (0.0, -1.2, 0.0),
            "ceiling": (0.0, 1.2, 0.0),
            "room_centre": (0.0, 0.0, 0.0),
        },
        "collider": ColliderBox(
            min_corner=(-2.4, -1.2, -2.4),
            max_corner=(2.4, 1.2, 2.4),
            floor_height=-1.2,
            ceiling_height=1.2,
            derivation="test",
        ),
        "splat_bounds": bounds,
        "cameras": cameras,
        "spawn": (0.0, -0.7, 0.0),
        "spawn_clearance_m": 0.5,
    }
    defaults.update(overrides)
    return FrameContract(**defaults)


class TestFrameContract:
    def test_valid_contract_passes(self):
        make_contract().validate()

    def test_round_trips_through_json(self, tmp_path):
        contract = make_contract()
        path = tmp_path / "m.json"
        contract.save(path)
        reloaded = FrameContract.load(path)
        assert reloaded.scene_id == contract.scene_id
        assert reloaded.ply_to_world.metres_per_unit == contract.ply_to_world.metres_per_unit
        assert reloaded.spawn == contract.spawn

    def test_rejects_scale_inconsistent_with_its_reference(self):
        contract = make_contract(
            ply_to_world=make_mapping(metres_per_unit=99.0),
            scale_reference=ScaleReference("chosen", "h", 0.48, 0.01, 12, 2.4, "test"),
        )
        with pytest.raises(ContractError, match="disagrees with its reference"):
            contract.validate()

    def test_rejects_up_axis_not_pointing_at_godot_up(self):
        # Identity basis declared z-up: frame +z still maps to Godot +z, so the
        # contract is internally inconsistent and must be refused.
        contract = make_contract(
            ply_to_world=make_mapping(
                basis_columns=((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)),
                up_axis="z",
            ),
        )
        with pytest.raises(ContractError, match="does not map onto Godot \\+Y"):
            contract.validate()

    def test_rejects_ceiling_below_floor(self):
        from splat_frame import ColliderBox

        contract = make_contract()
        broken = FrameContract(
            **{
                **contract.__dict__,
                "collider": ColliderBox(
                    min_corner=(-2.4, 1.2, -2.4),
                    max_corner=(2.4, -1.2, 2.4),
                    floor_height=1.2,
                    ceiling_height=-1.2,
                    derivation="test",
                ),
            }
        )
        with pytest.raises(ContractError, match="not above floor"):
            broken.validate()

    def test_rejects_spawn_outside_the_room(self):
        contract = make_contract(spawn=(99.0, -0.7, 0.0))
        with pytest.raises(ContractError, match="outside the collider room"):
            contract.validate()

    def test_rejects_spawn_at_the_wrong_clearance(self):
        contract = make_contract(spawn=(0.0, 5.0, 0.0))
        with pytest.raises(ContractError, match="outside the collider room|above the floor"):
            contract.validate()

    def test_rejects_missing_landmark(self):
        contract = make_contract(
            landmarks={"floor": (0.0, -1.2, 0.0), "ceiling": (0.0, 1.2, 0.0)}
        )
        with pytest.raises(ContractError):
            contract.validate()

    def test_rejects_unsupported_schema(self):
        contract = make_contract(schema_version=99)
        with pytest.raises(ContractError, match="schema_version"):
            contract.validate()

    def test_landmark_distance_is_the_clear_height(self):
        contract = make_contract()
        assert contract.landmark_distance("floor", "ceiling") == pytest.approx(2.4)

    def test_collider_height_interpolates(self):
        contract = make_contract()
        assert contract.collider_height(0.0) == pytest.approx(-1.2)
        assert contract.collider_height(1.0) == pytest.approx(1.2)
        assert contract.collider_height(0.5) == pytest.approx(0.0)

    def test_unknown_landmark_raises(self):
        with pytest.raises(ContractError, match="no landmark named"):
            make_contract().landmark("chimney")


# ---------------------------------------------------------------------------
# CameraPath: the reconstruction cameras inside the contract
# ---------------------------------------------------------------------------

class TestCameraPath:
    def test_round_trips_through_json(self, tmp_path):
        contract = make_contract()
        path = tmp_path / "m.json"
        contract.save(path)
        reloaded = FrameContract.load(path)
        assert reloaded.cameras == contract.cameras

    def test_records_the_camera_count(self):
        assert make_contract(cameras=CameraPath(
            count=7,
            world_min=(-1.0, -0.5, -1.0),
            world_max=(1.0, 0.5, 1.0),
            height_min_m=-0.5,
            height_mean_m=-0.5,
            height_max_m=0.5,
            source="test",
        )).cameras.count == 7

    def test_inside_room_accepts_a_path_within_the_room(self):
        contract = make_contract()
        assert contract.cameras.inside_room(contract.collider, 0.0)

    def test_inside_room_rejects_a_path_outside_the_room(self):
        contract = make_contract()
        # Shifted 3 m in x, well beyond any tolerance the contract uses.
        away = CameraPath(
            count=12,
            world_min=(3.0, -0.5, -1.0),
            world_max=(5.0, 0.5, 1.0),
            height_min_m=-0.5,
            height_mean_m=-0.5,
            height_max_m=0.5,
            source="test",
        )
        assert not away.inside_room(contract.collider, 2.0)

    def test_contract_rejects_an_empty_camera_path(self):
        with pytest.raises(ContractError, match="at least one camera"):
            make_contract(cameras=CameraPath(
                count=0,
                world_min=(0.0, 0.0, 0.0),
                world_max=(0.0, 0.0, 0.0),
                height_min_m=0.0,
                height_mean_m=0.0,
                height_max_m=0.0,
                source="none",
            )).validate()

    def test_contract_rejects_cameras_outside_the_room(self):
        outside = CameraPath(
            count=12,
            world_min=(-1.0, -0.5, -1.0),
            world_max=(1.0, 0.5, 12.0),
            height_min_m=-0.5,
            height_mean_m=-0.5,
            height_max_m=0.5,
            source="test",
        )
        with pytest.raises(ContractError, match="do not lie inside the room"):
            make_contract(cameras=outside).validate()

    def test_contract_rejects_cameras_above_the_ceiling(self):
        # The room on its side, or the up axis mapped to a horizontal one: the
        # cameras stay horizontally inside but rise above the ceiling.
        sideways = CameraPath(
            count=12,
            world_min=(-1.0, -0.5, -1.0),
            world_max=(1.0, 4.0, 1.0),
            height_min_m=3.9,
            height_mean_m=3.95,
            height_max_m=4.0,
            source="test",
        )
        with pytest.raises(ContractError):
            make_contract(cameras=sideways).validate()

    def test_contract_rejects_an_implausible_eye_height(self):
        # Cameras hugging the floor: below the 0.4 m band, which is what a scale
        # far too large (or a room far too small) looks like.
        crouched = CameraPath(
            count=12,
            world_min=(-1.0, -1.1, -1.0),
            world_max=(1.0, -1.05, 1.0),
            height_min_m=-1.1,
            height_mean_m=-1.07,
            height_max_m=-1.05,
            source="test",
        )
        with pytest.raises(ContractError, match="eye-height range"):
            make_contract(cameras=crouched).validate()

    def test_rejects_inverted_camera_bounds(self):
        # An inverted bound would otherwise be reported as "outside the room",
        # sending a reviewer after a coordinate bug instead of a corrupt record.
        inverted = CameraPath(
            count=12,
            world_min=(1.0, 0.5, 1.0),
            world_max=(-1.0, -0.5, -1.0),
            height_min_m=-0.5,
            height_mean_m=-0.5,
            height_max_m=0.5,
            source="test",
        )
        with pytest.raises(ContractError, match="inverted"):
            make_contract(cameras=inverted).validate()


# ---------------------------------------------------------------------------
# splat_geometry
# ---------------------------------------------------------------------------

def axis_normal(value: float, along: int = 2) -> np.ndarray:
    """A unit normal pointing along `along`, with `value` in the slot `along`."""
    normal = np.zeros(3)
    normal[along] = value
    return normal


class TestGaussianNormalAxes:
    def test_smallest_scale_row_is_the_normal(self):
        # A Gaussian flattened in z with an identity rotation is a floor splat:
        # its normal is +/-z. Identity rotation -> quaternion (w=1, x=y=z=0).
        scales = np.array([[1.0, 1.0, 0.01]])
        normals = splat_geometry.gaussian_normal_axes(scales, np.array([[1.0, 0.0, 0.0, 0.0]]))
        assert np.allclose(np.abs(normals[0]), [0.0, 0.0, 1.0])

    def test_normal_follows_the_rotation(self):
        # Same flattening, but rotated 90 degrees about y: the normal moves to x.
        half = np.sqrt(0.5)
        scales = np.array([[1.0, 1.0, 0.01]])
        quaternions = np.array([[half, 0.0, half, 0.0]])  # 90 deg about y
        normals = splat_geometry.gaussian_normal_axes(scales, quaternions)
        assert np.allclose(np.abs(normals[0]), [1.0, 0.0, 0.0], atol=1e-6)

    def test_normals_are_unit_length(self):
        quaternions = np.array([[1.0, 0.0, 0.0, 0.0], [0.7071, 0.7071, 0.0, 0.0]])
        scales = np.array([[1.0, 0.5, 0.01], [1.0, 0.5, 0.01]])
        normals = splat_geometry.gaussian_normal_axes(scales, quaternions)
        assert np.allclose(np.linalg.norm(normals, axis=1), 1.0)

    def test_rejects_degenerate_quaternion(self):
        with pytest.raises(ValueError):
            splat_geometry.gaussian_normal_axes(np.ones((1, 3)), np.zeros((1, 4)))

    def test_rejects_wrong_quaternion_shape(self):
        with pytest.raises(ValueError):
            splat_geometry.gaussian_normal_axes(np.ones((1, 3)), np.ones((1, 3)))


class TestPlaneMeasurement:
    """Floor/ceiling must come from mode *pairs*, never from the normal's sign.

    A covariance encodes an axis, not a facing, so splitting on sign finds the
    same sheet twice and reports a zero-thickness room. That is a bug that shipped.
    """

    def build_room(self, floor=0.0, ceiling=2.0, sheet=3000, background=3000, span=(-1.0, 1.0)):
        """A room with two dense sheets plus a sparse volumetric background.

        The background matters: plane detection judges a surface by how much
        denser it is than the axis background, so two sheets alone give a
        background equal to the peak and no surface is detectable at all.
        """
        rng = np.random.default_rng(20260928)
        points = []
        normals = []
        for height, facing in ((floor, 1.0), (ceiling, -1.0)):
            sheet_points = np.column_stack([
                rng.uniform(span[0], span[1], sheet),
                rng.uniform(span[0], span[1], sheet),
                np.full(sheet, height),
            ])
            points.append(sheet_points)
            normals.append(np.tile([0.0, 0.0, facing], (sheet, 1)))
        points.append(rng.uniform([span[0], span[0], floor], [span[1], span[1], ceiling], (background, 3)))
        normals.append(rng.normal(size=(background, 3)))
        return np.vstack(points), np.vstack(normals)

    def test_measures_clear_height(self):
        points, normals = self.build_room()
        height, spread, stations = splat_geometry.measure_clear_height(points, normals, up_axis=2)
        assert height == pytest.approx(2.0, abs=0.05)
        assert spread >= 0.0
        assert stations >= splat_geometry.MIN_SPREAD_SAMPLES

    def test_plane_pair_is_independent_of_normal_sign(self):
        """Flipping every normal must not change the measured pair."""
        points, normals = self.build_room()
        lower, upper, _, _ = splat_geometry.measure_room_bounds(points, normals, up_axis=2)
        flipped_lower, flipped_upper, _, _ = splat_geometry.measure_room_bounds(points, -normals, up_axis=2)
        assert lower.offset == pytest.approx(0.0, abs=0.05)
        assert upper.offset == pytest.approx(2.0, abs=0.05)
        assert flipped_lower.offset == pytest.approx(lower.offset, abs=1e-6)
        assert flipped_upper.offset == pytest.approx(upper.offset, abs=1e-6)

    def test_plane_pair_returns_low_offset_first(self):
        points, normals = self.build_room()
        lower, upper, _, _ = splat_geometry.measure_room_bounds(points, normals, up_axis=2)
        assert lower.offset < upper.offset

    def test_rejects_an_unmeasurable_axis(self):
        points = np.random.uniform(-1.0, 1.0, size=(600, 3))
        normals = np.tile([1.0, 1.0, 1.0] / np.sqrt(3.0), (600, 1))
        with pytest.raises(splat_geometry.MeasurementError):
            splat_geometry.measure_plane_pair(points, normals, axis=2, bin_width=0.02, min_separation=0.05)

    def test_plane_strength_is_low_for_a_blob_and_high_for_a_room(self):
        room_points, room_normals = self.build_room()
        blob_points = np.random.uniform(-1.0, 1.0, size=(600, 3))
        blob_normals = np.tile([0.0, 0.0, 1.0], (600, 1))
        assert splat_geometry.measure_plane_strength(room_points, room_normals, 2) >= splat_geometry.MIN_MODE_CONTRAST
        assert splat_geometry.measure_plane_strength(blob_points, blob_normals, 0) == 0.0

    def test_rejects_a_too_few_corridor_stations(self):
        points = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 1.0]])
        normals = np.array([[0.0, 0.0, 1.0], [0.0, 0.0, -1.0]])
        with pytest.raises(splat_geometry.MeasurementError):
            splat_geometry.measure_clear_height(points, normals, up_axis=2)


class TestDominantModes:
    def test_finds_two_separated_peaks(self):
        values = np.concatenate([
            np.random.normal(0.0, 0.02, 1000),
            np.random.normal(2.0, 0.02, 1000),
        ])
        modes = splat_geometry._dominant_modes(values, bin_width=0.02, min_separation=0.5, count=2)
        assert len(modes) == 2
        centres = sorted(mode[0] for mode in modes)
        assert centres[0] == pytest.approx(0.0, abs=0.05)
        assert centres[1] == pytest.approx(2.0, abs=0.05)

    def test_respects_minimum_separation(self):
        values = np.concatenate([
            np.random.normal(0.0, 0.02, 500),
            np.random.normal(0.1, 0.02, 500),
        ])
        modes = splat_geometry._dominant_modes(values, bin_width=0.01, min_separation=0.5, count=2)
        # One broad peak; the near neighbour is inside min_separation.
        assert len(modes) == 1

    def test_rejects_nonpositive_bin_width(self):
        with pytest.raises(ValueError):
            splat_geometry._dominant_modes(np.zeros(10), bin_width=0.0, min_separation=0.1, count=2)

    def test_rejects_nonpositive_separation(self):
        with pytest.raises(ValueError):
            splat_geometry._dominant_modes(np.zeros(10), bin_width=0.1, min_separation=0.0, count=2)


# ---------------------------------------------------------------------------
# COLMAP model reading
# ---------------------------------------------------------------------------

def write_colmap_images(path: Path, records: list[dict]) -> None:
    """Write a COLMAP images.bin from simple records."""
    with path.open("wb") as handle:
        handle.write(struct.pack("<Q", len(records)))
        for record in records:
            handle.write(struct.pack("<i", record["image_id"]))
            handle.write(struct.pack("<4d", *record["qvec"]))
            handle.write(struct.pack("<3d", *record["tvec"]))
            handle.write(struct.pack("<i", record["camera_id"]))
            handle.write(record["name"].encode("ascii") + b"\x00")
            handle.write(struct.pack("<Q", 0))


class TestColmapModel:
    def test_camera_centre_from_quaternion(self, tmp_path):
        write_colmap_images(tmp_path / "images.bin", [
            {"image_id": 1, "qvec": (1.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, 5.0),
             "camera_id": 1, "name": "a.jpg"},
        ])
        images = colmap_model.read_images(tmp_path)
        # identity rotation, t = +5 z -> camera centre at -5 z
        assert np.allclose(images[0].camera_center, [0.0, 0.0, -5.0])

    def test_view_and_up_directions_use_colmap_convention(self, tmp_path):
        write_colmap_images(tmp_path / "images.bin", [
            {"image_id": 1, "qvec": (1.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, 0.0),
             "camera_id": 1, "name": "a.jpg"},
        ])
        image = colmap_model.read_images(tmp_path)[0]
        # COLMAP: +Z forward, +Y down, +X right
        assert np.allclose(image.view_direction, [0.0, 0.0, 1.0])
        assert np.allclose(image.up_direction, [0.0, -1.0, 0.0])
        assert np.allclose(image.right_direction, [1.0, 0.0, 0.0])

    def test_up_direction_uses_majority_not_mean(self, tmp_path):
        """One flipped pose must not invert the scene's up axis."""
        records = [{"image_id": i, "qvec": (1.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, 0.0),
                    "camera_id": 1, "name": f"{i}.jpg"} for i in range(9)]
        # Flip one camera by 180 degrees about x: q = (0, 1, 0, 0)
        records[0]["qvec"] = (0.0, 1.0, 0.0, 0.0)
        write_colmap_images(tmp_path / "images.bin", records)
        images = colmap_model.read_images(tmp_path)
        up = colmap_model.dominant_up_direction(images)
        assert up[1] < 0.0

    def test_principal_axis_index(self, tmp_path):
        write_colmap_images(tmp_path / "images.bin", [
            {"image_id": 1, "qvec": (1.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, 0.0),
             "camera_id": 1, "name": "a.jpg"},
        ])
        up = colmap_model.dominant_up_direction(colmap_model.read_images(tmp_path))
        index, magnitude = colmap_model.dominant_up_axis_index(up)
        assert index == 1
        assert magnitude < 0.0

    def test_rejects_degenerate_quaternion(self, tmp_path):
        write_colmap_images(tmp_path / "images.bin", [
            {"image_id": 1, "qvec": (0.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, 0.0),
             "camera_id": 1, "name": "a.jpg"},
        ])
        with pytest.raises(ValueError):
            colmap_model.read_images(tmp_path)

    def test_empty_model_has_no_up_direction(self, tmp_path):
        write_colmap_images(tmp_path / "images.bin", [])
        with pytest.raises(ValueError):
            colmap_model.dominant_up_direction([])

    def test_camera_centers_stacks(self, tmp_path):
        write_colmap_images(tmp_path / "images.bin", [
            {"image_id": 1, "qvec": (1.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, 0.0),
             "camera_id": 1, "name": "a.jpg"},
            {"image_id": 2, "qvec": (1.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, -2.0),
             "camera_id": 1, "name": "b.jpg"},
        ])
        centres = colmap_model.camera_centers(colmap_model.read_images(tmp_path))
        assert centres.shape == (2, 3)
        assert np.allclose(centres[1], [0.0, 0.0, 2.0])

    def test_reads_cameras_bin(self, tmp_path):
        with (tmp_path / "cameras.bin").open("wb") as handle:
            handle.write(struct.pack("<Q", 1))
            handle.write(struct.pack("<iiQQ", 7, 0, 1920, 1080))  # 0 = SIMPLE_PINHOLE
            handle.write(struct.pack("<3d", 1000.0, 960.0, 540.0))
        cameras = colmap_model.read_cameras(tmp_path)
        assert cameras[7].model == "SIMPLE_PINHOLE"
        assert cameras[7].width == 1920
        assert cameras[7].params == (1000.0, 960.0, 540.0)

    def test_rejects_an_unknown_camera_model(self, tmp_path):
        with (tmp_path / "cameras.bin").open("wb") as handle:
            handle.write(struct.pack("<Q", 1))
            handle.write(struct.pack("<iiQQ", 7, 999, 1920, 1080))
            handle.write(b"\x00" * 8)
        with pytest.raises(ValueError, match="unsupported COLMAP camera model"):
            colmap_model.read_cameras(tmp_path)

    def test_find_sparse_model_prefers_most_cameras(self, tmp_path):
        for name, count in (("sparse/0", 2), ("sparse/1", 9)):
            directory = tmp_path / name
            directory.mkdir(parents=True)
            write_colmap_images(directory / "images.bin", [
                {"image_id": i, "qvec": (1.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, 0.0),
                 "camera_id": 1, "name": f"{i}.jpg"} for i in range(count)
            ])
            (directory / "cameras.bin").write_bytes(b"")
        assert colmap_model.find_sparse_model(tmp_path).name == "1"

    def test_find_sparse_model_honours_preference(self, tmp_path):
        for name in ("sparse/0", "sparse/1"):
            directory = tmp_path / name
            directory.mkdir(parents=True)
            write_colmap_images(directory / "images.bin", [
                {"image_id": 0, "qvec": (1.0, 0.0, 0.0, 0.0), "tvec": (0.0, 0.0, 0.0),
                 "camera_id": 1, "name": "a.jpg"}
            ])
            (directory / "cameras.bin").write_bytes(b"")
        assert colmap_model.find_sparse_model(tmp_path, prefer="sparse/0").name == "0"

    def test_find_sparse_model_reports_missing(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            colmap_model.find_sparse_model(tmp_path)


# ---------------------------------------------------------------------------
# manifest_rules: the recorded automatic-transform table
# ---------------------------------------------------------------------------

class TestManifestRules:
    def test_records_every_automatic_transform_stage(self):
        from manifest_rules import automatic_transforms

        stages = {entry.stage for entry in automatic_transforms()}
        assert stages == {"import", "node_enter_tree", "render"}

    def test_documents_the_gdgs_orientation_correction(self):
        from manifest_rules import GDGS_DEFAULT_CORRECTION, automatic_transforms

        entry = next(e for e in automatic_transforms() if e.stage == "node_enter_tree")
        assert entry.basis == GDGS_DEFAULT_CORRECTION
        # It preserves the up axis, which is why it cannot fix a z-up splat.
        assert entry.basis[2][2] == 1.0
        assert entry.neutralised is True
        assert entry.neutralised_by

    def test_records_the_builder_centroid_subtraction(self):
        from manifest_rules import automatic_transforms

        entry = next(e for e in automatic_transforms() if "builder" in e.source)
        assert entry.neutralised is False
        assert entry.origin == (0.0, 0.0, 0.0)

    def test_records_the_shader_covariance_transform(self):
        from manifest_rules import automatic_transforms

        entry = next(e for e in automatic_transforms() if e.stage == "render")
        assert "covariance" in entry.summary.lower()

    def test_rejects_the_retired_mesh_scale(self):
        from manifest_rules import rejected_scales

        values = {entry["value"] for entry in rejected_scales()}
        assert "0.800977" in values
        retired = next(e for e in rejected_scales() if e["value"] == "0.800977")
        assert "poisson" in retired["why"].lower()
        assert retired["why"]

    def test_rejects_unscaled_loading(self):
        from manifest_rules import rejected_scales

        assert any(entry["value"] == "1.0" for entry in rejected_scales())