#!/usr/bin/env python3
"""End-to-end tests for the capture gate against repeatable synthetic clips.

This is where the accepted/rejected fixture pairs earn their keep: each clip has
a known property, so the verdict is asserted against a property rather than
against a recording of what the code used to print. The clips are generated by
``fixtures/make_capture_fixtures.py``, so the whole file is reproducible on any
machine with ffmpeg and numpy and no shipped footage.

Two things are checked that a unit test cannot be:

* the fixtures really do have the properties they claim (a "moving content"
  fixture whose moving object covers 0.1% of the frame would silently stop
  testing anything);
* the bounded-work promise holds -- the long clip must not cost more than the
  short one by an amount that tracks its length.

Needs ffmpeg and ffprobe. Skipped, not failed, when they are absent.

Run from ``scripts/splat_pipeline``:
    python3 -m pytest tests/test_capture_fixtures.py -q
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import capture_gate
import capture_verdict
import sample_frames
from candidate_scan import candidate_stride_for, scan_capture, scan_bursts
from frame_reader import analysis_size, frame_timestamp, seek_candidates, stream_candidates
from fixtures.make_capture_fixtures import FIXTURES, FixtureError, build_all
from geometry_consistency import INCOHERENT, classify_consistency
from sampling_budget import SamplingBudget
from video_probe import VideoProbeError, probe_video

PIPELINE_DIR = Path(__file__).resolve().parent.parent
CLIP_DIR = PIPELINE_DIR / "fixtures" / "clips"

pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="the capture gate needs ffmpeg and ffprobe",
)

#: Clip length the long-clip comparison uses. Long enough to be visibly longer
#: than the budget and still fast to decode twice.
LONG_CLIP = "long_walkthrough"


@pytest.fixture(scope="session")
def clips(tmp_path_factory) -> dict[str, Path]:
    """Build every fixture once per session into a temporary directory."""
    output = tmp_path_factory.mktemp("clips")
    try:
        built = build_all(output)
    except FixtureError as exc:
        pytest.skip(f"could not build the capture fixtures: {exc}")
    return {fixture.name: path for fixture, path in built}


def budget_for(name: str, **overrides) -> SamplingBudget:
    """A budget sized for one fixture, with the overrides applied."""
    defaults = {
        "target_frames": 150,
        "max_candidates": 240,
        "decode_mode": "stream",
    }
    defaults.update(overrides)
    return SamplingBudget(**defaults)


def gate(clips: dict[str, Path], name: str, **overrides) -> dict:
    """Run the whole gate over one fixture and return its report."""
    return capture_gate.run_gate(clips[name], budget_for(name, **overrides), clips[name].parent)


# --------------------------------------------------------------------------
# The probes the fixture properties depend on
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "name,frames,size,expected",
    [(fixture.name, fixture.frames, fixture.size, fixture.expected) for fixture in FIXTURES],
)
def test_every_fixture_builds_and_is_a_readable_video(clips, name, frames, size, expected):
    """The fixture table and the generated clips must not drift apart."""
    video = clips[name]
    metadata = probe_video(video)
    assert metadata.width == size[0]
    assert metadata.height == size[1]
    assert abs(metadata.frame_count - frames) <= 1
    assert metadata.frame_count_is_exact or metadata.fps > 0


def test_the_accepted_walk_has_real_translation(clips):
    scan = scan_capture(probe_video(clips["accepted_walkthrough"]), budget_for("accepted_walkthrough"))
    fractions = [
        candidate.translation.magnitude_fraction
        for candidate in scan.candidates
        if candidate.translation is not None
    ]
    assert float(np.median(fractions)) > 0.005


def test_the_stationary_fixture_really_is_stationary(clips):
    """Otherwise the rejection test would pass for the wrong reason."""
    scan = scan_capture(probe_video(clips["stationary_camera"]), budget_for("stationary_camera"))
    fractions = [
        candidate.translation.magnitude_fraction
        for candidate in scan.candidates
        if candidate.translation is not None
    ]
    assert float(np.median(fractions)) < 0.005


def test_the_cut_fixture_really_has_cuts(clips):
    scan = scan_capture(probe_video(clips["cut_sequence"]), budget_for("cut_sequence"))
    assert any(candidate.is_cut for candidate in scan.candidates)


def test_the_accepted_walk_really_has_no_cuts(clips):
    scan = scan_capture(probe_video(clips["accepted_walkthrough"]), budget_for("accepted_walkthrough"))
    assert not any(candidate.is_cut for candidate in scan.candidates)


def test_the_incoherent_fixture_is_classified_as_inconsistent(clips):
    scan = scan_capture(probe_video(clips["incoherent_geometry"]), budget_for("incoherent_geometry"))
    assert classify_consistency(scan.bursts).classification == INCOHERENT


def test_the_moving_fixture_is_not_classified_as_inconsistent(clips):
    """A moving object is a warning; calling it incoherent would refuse a usable take."""
    scan = scan_capture(probe_video(clips["moving_content"]), budget_for("moving_content"))
    verdict = classify_consistency(scan.bursts)
    assert verdict.classification != INCOHERENT
    assert verdict.rejected is False


def test_720p_is_scored_at_the_same_analysis_resolution_as_1080p_would_be(clips):
    """Scaling the analysis frame down is what makes the numbers comparable."""
    for name in ("accepted_720p", "accepted_walkthrough"):
        size = analysis_size(probe_video(clips[name]), SamplingBudget().analysis_max_pixels)
        assert size.width == 640 and size.height == 360


# --------------------------------------------------------------------------
# Verdicts: the accepted/rejected contract
# --------------------------------------------------------------------------


@pytest.mark.parametrize("name", ["accepted_walkthrough", "accepted_720p"])
def test_accepted_fixtures_are_accepted(clips, name):
    report = gate(clips, name)
    assert report["verdict"]["status"] == capture_verdict.STATUS_ACCEPTED
    assert report["verdict"]["findings"] == [] or all(
        finding["severity"] != capture_verdict.SEVERITY_BLOCK for finding in report["verdict"]["findings"]
    )


@pytest.mark.parametrize(
    "name", ["stationary_camera", "cut_sequence", "incoherent_geometry"]
)
def test_rejected_fixtures_are_rejected(clips, name):
    report = gate(clips, name)
    assert report["verdict"]["status"] == capture_verdict.STATUS_REJECTED


def test_every_rejection_carries_a_capture_action(clips):
    for name in ("stationary_camera", "cut_sequence", "incoherent_geometry"):
        report = gate(clips, name)
        blocking = [
            finding for finding in report["verdict"]["findings"]
            if finding["severity"] == capture_verdict.SEVERITY_BLOCK
        ]
        assert blocking, f"{name} was rejected with no blocking finding"
        for finding in blocking:
            assert finding["action"].strip(), f"{name}/{finding['code']} has no action"
            assert finding["cause"].strip(), f"{name}/{finding['code']} has no cause"


def test_720p_is_not_rejected_on_resolution(clips):
    """The specific wrong behaviour this issue had to undo, on a real clip."""
    report = gate(clips, "accepted_720p")
    blocking_codes = {
        finding["code"]
        for finding in report["verdict"]["findings"]
        if finding["severity"] == capture_verdict.SEVERITY_BLOCK
    }
    assert "resolution_below_recommended" not in blocking_codes
    assert "resolution_unusable" not in blocking_codes
    assert report["verdict"]["status"] == capture_verdict.STATUS_ACCEPTED


def test_the_moving_content_fixture_is_accepted_with_warnings(clips):
    report = gate(clips, "moving_content")
    assert report["verdict"]["status"] == capture_verdict.STATUS_WARNED


# --------------------------------------------------------------------------
# Bounded work
# --------------------------------------------------------------------------


def test_sampling_cost_does_not_track_clip_length(clips):
    """A 900-frame clip must not cost 9x a 96-frame one to sample.

    The budget is on selected frames and analysis pixels, not on the length of
    the input, so the two clips are compared with the same target. Both are
    sampled by a stream that visits every frame, so a strict bound does not hold
    -- what must hold is that the ratio stays far below the 9.4x length ratio,
    because the retained set is what the budget bounds.
    """
    short = gate(clips, "accepted_walkthrough")
    long_report = gate(clips, LONG_CLIP)
    length_ratio = probe_video(clips[LONG_CLIP]).frame_count / probe_video(
        clips["accepted_walkthrough"]
    ).frame_count
    time_ratio = long_report["seconds"] / max(short["seconds"], 1e-9)
    assert time_ratio < length_ratio / 2, (
        f"sampling the long clip took {time_ratio:.1f}x the short clip's time for a "
        f"{length_ratio:.1f}x longer input -- the cost is not bounded"
    )


def test_the_long_clip_keeps_only_a_bounded_fraction_of_its_frames(clips):
    report = gate(clips, LONG_CLIP)
    retained = report["scan"]["decode"]["candidates"]["retained"]
    total = report["scan"]["decode"]["candidates"]["clip_frames"]
    assert retained <= SamplingBudget().max_candidates
    assert retained < total / 2


def test_the_long_clip_selection_lands_inside_the_frame_hypothesis(clips):
    report = gate(clips, LONG_CLIP)
    selected = report["selection"]["selected_count"]
    assert 100 <= selected <= 200


def test_every_dropped_frame_is_accounted_for(clips):
    """Excluded plus selected must equal what was scored -- no silent losses."""
    for name in ("accepted_walkthrough", "cut_sequence", "moving_content"):
        report = gate(clips, name)
        scored = len(report["scan"]["candidates"])
        selected = report["selection"]["selected_count"]
        excluded = len(report["selection"]["exclusions"])
        assert selected + excluded == scored


@pytest.mark.parametrize("motion", [2.0, 3.0, 5.0])
def test_the_candidate_cap_widens_the_stride_for_a_longer_clip(clips, motion):
    """The stride is the wider of two constraints; on a long clip the cap binds.

    The motion constraint alone would keep the stride fixed, which is what bounds
    the *quality* of each sample. What has to grow with clip length is the
    stride, so the number of candidates stays inside ``max_candidates`` --
    otherwise a long clip scores 900 frames and the budget bounds nothing.
    """
    budget = SamplingBudget()
    width = analysis_size(probe_video(clips[LONG_CLIP]), budget.analysis_max_pixels).width
    long_frames = probe_video(clips[LONG_CLIP]).frame_count
    long_stride = candidate_stride_for(long_frames, motion, width, budget)
    short_stride = candidate_stride_for(96, motion, width, budget)
    assert long_stride > short_stride
    assert -(-long_frames // long_stride) <= budget.max_candidates


def test_the_stride_for_a_long_clip_is_measured_from_that_clip_not_a_guess(clips):
    """Asserting the cap bound, so the bound is not the only thing under test."""
    budget = SamplingBudget()
    scan = scan_capture(probe_video(clips[LONG_CLIP]), budget)
    expected = candidate_stride_for(scan.metadata.frame_count, scan.motion_px_per_frame, scan.size.width, budget)
    assert scan.stride == expected
    assert len(scan.candidates) <= budget.max_candidates


def test_the_scan_states_what_it_did_not_measure(clips):
    report = gate(clips, "accepted_walkthrough")
    limits = report["verdict"]["limits"]
    assert limits
    joined = " ".join(limits)
    assert "full" in joined and "source" in joined


# --------------------------------------------------------------------------
# Extraction
# --------------------------------------------------------------------------


def test_extraction_writes_exactly_the_selected_frames_at_source_resolution(clips, tmp_path):
    report = gate(clips, "accepted_walkthrough")
    destination = tmp_path / "images"
    extraction = sample_frames.extract_selection(report, clips["accepted_walkthrough"], destination)
    assert extraction.frames_written == len(report["selection"]["selected"])
    written = sorted(path.name for path in destination.glob("frame_*.jpg"))
    assert len(written) == extraction.frames_written
    # The analysis frames are downscaled; the written frames must not be.
    assert extraction.analysis_resolution == extraction.source_resolution


def test_extraction_of_a_720p_capture_preserves_the_source_resolution(clips, tmp_path):
    report = gate(clips, "accepted_720p")
    destination = tmp_path / "images"
    sample_frames.extract_selection(report, clips["accepted_720p"], destination)
    probe = subprocess.run(
        [
            "ffprobe", "-v", "error", "-select_streams", "v:0",
            "-show_entries", "stream=width,height", "-of", "csv=p=0:s=x",
            str(destination / "frame_0001.jpg"),
        ],
        capture_output=True, text=True, check=True,
    )
    assert probe.stdout.strip() == "1280x720"


def test_extraction_maps_every_written_frame_back_to_its_source_index(clips, tmp_path):
    report = gate(clips, "accepted_walkthrough")
    destination = tmp_path / "images"
    sample_frames.extract_selection(report, clips["accepted_walkthrough"], destination)
    manifest = json.loads((destination / "frames.json").read_text(encoding="utf-8"))
    entries = manifest["frames"]
    assert [entry["source_frame_index"] for entry in entries] == report["selection"]["selected"]
    assert [entry["file"] for entry in entries] == [
        f"frame_{index:04d}.jpg" for index in range(1, len(entries) + 1)
    ]


def test_extraction_costs_one_seek_per_frame_not_a_pass_over_the_clip(clips, tmp_path):
    report = gate(clips, LONG_CLIP)
    extraction = sample_frames.extract_selection(
        report, clips[LONG_CLIP], tmp_path / "images", dry_run=True
    )
    assert extraction.invocations == 0  # a dry run decodes nothing
    assert extraction.frames_expected == len(report["selection"]["selected"])
    assert extraction.frames_expected <= SamplingBudget().target_frames


def test_extraction_refuses_a_report_with_no_selection(clips, tmp_path):
    with pytest.raises(sample_frames.SelectionError, match="selected no frames"):
        sample_frames.extract_selection(
            {"selection": {"selected": []}, "verdict": {"status": "rejected"}},
            clips["accepted_walkthrough"],
            tmp_path / "images",
        )


def test_extraction_refuses_a_report_with_no_selection_section(clips, tmp_path):
    with pytest.raises(sample_frames.SelectionError, match="no 'selection' section"):
        sample_frames.extract_selection({}, clips["accepted_walkthrough"], tmp_path / "images")


def test_extraction_removes_frames_from_a_previous_extraction(clips, tmp_path):
    report = gate(clips, "accepted_walkthrough")
    destination = tmp_path / "images"
    destination.mkdir()
    stale = destination / "frame_0999.jpg"
    stale.write_bytes(b"stale")
    sample_frames.extract_selection(report, clips["accepted_walkthrough"], destination)
    assert not stale.exists()


def test_the_written_frame_is_the_frame_the_gate_selected(clips, tmp_path):
    """The seek convention has to land on the chosen index, not the one after it.

    ffmpeg's accurate ``-ss`` returns the first frame at or after the target, so
    a half-frame offset would silently write the *next* frame -- and on the last
    frame of a clip it writes nothing at all.
    """
    video = clips["accepted_walkthrough"]
    metadata = probe_video(video)
    size = analysis_size(metadata, 64 * 36)
    streamed = stream_candidates(video, size, stride=1, clip_frames=metadata.frame_count)
    by_index = dict(zip(streamed.indices, streamed.frames))

    for index in (0, 1, 40, 94, 95):
        sought = seek_candidates(video, size, [index], metadata.fps)
        assert sought.indices == (index,), f"seek reported frame {sought.indices} for {index}"
        difference = abs(sought.frames[0].astype(int) - by_index[index].astype(int)).mean()
        assert difference == 0, f"seek for frame {index} differs by {difference:.2f} grey levels"


def test_frame_timestamp_is_the_frames_own_presentation_time():
    assert frame_timestamp(24, 24.0) == pytest.approx(1.0)
    assert frame_timestamp(0, 24.0) == 0.0


def test_frame_timestamp_falls_back_when_the_rate_is_unknown():
    assert frame_timestamp(25, 0.0) == pytest.approx(25 / 25.0)


def test_seeking_the_last_frame_returns_it_rather_than_nothing(clips):
    video = clips["accepted_walkthrough"]
    metadata = probe_video(video)
    size = analysis_size(metadata, 64 * 36)
    last = metadata.frame_count - 1
    sought = seek_candidates(video, size, [last], metadata.fps)
    assert sought.frames, "the final frame of a clip must be reachable by seek"


# --------------------------------------------------------------------------
# Bursts and probes
# --------------------------------------------------------------------------


def test_a_burst_probe_on_a_real_clip_measures_something(clips):
    stats, decoded = scan_bursts(probe_video(clips["accepted_walkthrough"]), SamplingBudget())
    assert stats.pairs > 0
    assert decoded > 0


def test_a_burst_probe_declines_to_measure_when_no_window_decodes(clips):
    """A one-frame clip has no adjacent pair; it must say so rather than guess."""
    stats, decoded = scan_bursts(
        probe_video(clips["accepted_walkthrough"]),
        SamplingBudget(burst_count=1, burst_length=1),
    )
    assert stats.pairs == 0
    assert classify_consistency(stats).rejected is False


def test_probe_reports_its_own_work(clips):
    report = gate(clips, "accepted_walkthrough")
    decode = report["scan"]["decode"]
    for stage in ("probe", "candidates"):
        assert decode[stage]["visited"] > 0
        assert decode[stage]["seconds"] >= 0


# --------------------------------------------------------------------------
# CLI surface
# --------------------------------------------------------------------------


def test_gate_cli_exits_zero_for_an_accepted_capture(clips, tmp_path):
    result = subprocess.run(
        [sys.executable, "capture_gate.py", str(clips["accepted_walkthrough"]), "--json", str(tmp_path / "r.json")],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 0, result.stderr
    assert "VERDICT: ACCEPTED" in result.stdout


def test_gate_cli_exits_three_for_a_rejected_capture(clips):
    result = subprocess.run(
        [sys.executable, "capture_gate.py", str(clips["stationary_camera"])],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 3, result.stdout + result.stderr


def test_gate_cli_writes_the_report_it_prints(clips, tmp_path):
    path = tmp_path / "report.json"
    subprocess.run(
        [sys.executable, "capture_gate.py", str(clips["accepted_walkthrough"]), "--json", str(path)],
        capture_output=True, text=True, cwd=PIPELINE_DIR, check=True,
    )
    report = json.loads(path.read_text(encoding="utf-8"))
    assert report["verdict"]["status"] == capture_verdict.STATUS_ACCEPTED
    for section in ("metadata", "budget", "scan", "selection", "coverage", "matching", "resource_estimate"):
        assert section in report


def test_gate_cli_exits_one_for_a_missing_file(tmp_path):
    result = subprocess.run(
        [sys.executable, "capture_gate.py", str(tmp_path / "absent.mp4")],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 1


def test_gate_cli_exits_four_for_an_unreadable_input(tmp_path):
    broken = tmp_path / "broken.mp4"
    broken.write_bytes(b"this is not a video")
    result = subprocess.run(
        [sys.executable, "capture_gate.py", str(broken)],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 4


def test_gate_run_honours_a_budget_file(clips, tmp_path):
    import sampling_budget

    budget_path = tmp_path / "budget.json"
    budget_path.write_text('{"target_frames": 12}', encoding="utf-8")
    budget = sampling_budget.load_json(budget_path)
    assert budget.target_frames == 12
    report = capture_gate.run_gate(clips[LONG_CLIP], budget, clips[LONG_CLIP].parent)
    assert report["budget"]["target_frames"] == 12


def test_gate_cli_honours_a_budget_file(clips, tmp_path):
    budget_path = tmp_path / "budget.json"
    budget_path.write_text('{"target_frames": 12}', encoding="utf-8")
    result = subprocess.run(
        [
            sys.executable, "capture_gate.py", str(clips[LONG_CLIP]),
            "--budget", str(budget_path), "--json", str(tmp_path / "r.json"),
        ],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 0, result.stderr
    report = json.loads((tmp_path / "r.json").read_text(encoding="utf-8"))
    assert report["budget"]["target_frames"] == 12
    assert report["selection"]["selected_count"] <= 12


def test_gate_cli_rejects_a_budget_value_it_cannot_use(clips, tmp_path):
    budget_path = tmp_path / "budget.json"
    budget_path.write_text('{"target_frames": 0}', encoding="utf-8")
    result = subprocess.run(
        [sys.executable, "capture_gate.py", str(clips["accepted_walkthrough"]), "--budget", str(budget_path)],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 1
    assert "target_frames" in result.stderr


def test_sample_frames_cli_writes_frames(clips, tmp_path):
    report_path = tmp_path / "report.json"
    subprocess.run(
        [sys.executable, "capture_gate.py", str(clips["accepted_walkthrough"]), "--json", str(report_path)],
        capture_output=True, text=True, cwd=PIPELINE_DIR, check=True,
    )
    destination = tmp_path / "images"
    result = subprocess.run(
        [
            sys.executable, "sample_frames.py", str(clips["accepted_walkthrough"]),
            str(report_path), "--out", str(destination),
        ],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 0, result.stderr
    assert list(destination.glob("frame_*.jpg"))
    assert "EXTRACTION" in result.stdout


def test_sample_frames_cli_dry_run_writes_nothing(clips, tmp_path):
    report_path = tmp_path / "report.json"
    subprocess.run(
        [sys.executable, "capture_gate.py", str(clips["accepted_walkthrough"]), "--json", str(report_path)],
        capture_output=True, text=True, cwd=PIPELINE_DIR, check=True,
    )
    destination = tmp_path / "images"
    result = subprocess.run(
        [
            sys.executable, "sample_frames.py", str(clips["accepted_walkthrough"]),
            str(report_path), "--out", str(destination), "--dry-run",
        ],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 0, result.stderr
    assert not destination.exists() or not list(destination.glob("frame_*"))


def test_sample_frames_cli_exits_one_without_a_report(tmp_path):
    result = subprocess.run(
        [sys.executable, "sample_frames.py", str(tmp_path / "a.mp4"), str(tmp_path / "absent.json")],
        capture_output=True, text=True, cwd=PIPELINE_DIR,
    )
    assert result.returncode == 1


def test_probe_rejects_a_file_with_no_video_stream(tmp_path):
    audio = tmp_path / "audio.m4a"
    result = subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-f", "lavfi", "-i", "sine=frequency=440:duration=1", str(audio)],
        capture_output=True, cwd=PIPELINE_DIR,
    )
    if result.returncode != 0 or not audio.is_file():
        pytest.skip("could not encode an audio-only test file")
    with pytest.raises(VideoProbeError, match="no video stream"):
        probe_video(audio)


def test_probe_rejects_a_missing_file(tmp_path):
    with pytest.raises(VideoProbeError, match="file not found"):
        probe_video(tmp_path / "absent.mp4")
