#!/usr/bin/env python3
"""Tests for bounded, deterministic splat cleanup.

These cover the pure mask logic and the PLY subset writer, so the expensive
filtered-derivative run does not have to be repeated to know the cleanup still
does what the report says it does. The properties that matter:

* the crop is a hard world-space box, so a far-field floater is removed for
  being outside it -- not for being faint, which the shipped floaters are not;
* every threshold is an explicit parameter, so the kept set is reproducible
  from the report alone;
* per-stage counts are disjoint and sum to the number removed;
* the derivative keeps the source's property layout and changes only the count;
* the node translation compensates for GDGS re-centring the filtered cloud.

Run with: python3 -m pytest scripts/splat_pipeline/tests/test_splat_cleanup.py -v
"""

from __future__ import annotations

import json
import struct
import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import clean_splat
import splat_cleanup
import splat_frame
from splat_cleanup import CleanupParams, compute_keep_mask

MANIFEST = (
    Path(__file__).resolve().parent.parent.parent.parent
    / "godot_walk"
    / "assets"
    / "corridor_splat"
    / "alignment_manifest.json"
)

PROPERTIES = ["x", "y", "z", "scale_0", "scale_1", "scale_2", "opacity"]


def write_ply(path: Path, rows: list[dict]) -> None:
    """Write a minimal binary_little_endian PLY with the given rows."""
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment Generated by test\n"
        f"element vertex {len(rows)}\n"
        + "".join(f"property float {name}\n" for name in PROPERTIES)
        + "end_header\n"
    )
    body = b"".join(
        struct.pack("<%df" % len(PROPERTIES), *[float(row.get(name, 0.0)) for name in PROPERTIES])
        for row in rows
    )
    path.write_bytes(header.encode("ascii") + body)


def raw_for(world: np.ndarray, mapping) -> np.ndarray:
    """Invert the PLY->world mapping for a chosen world point."""
    rotation = mapping.rotation()
    origin = np.asarray(mapping.origin_ply_units, dtype=np.float64)
    return rotation.T @ (np.asarray(world, dtype=np.float64) / mapping.metres_per_unit) + origin


class TestPureHelpers:
    def test_sigmoid_matches_the_renderer_convention(self):
        value = splat_cleanup.sigmoid_opacity(np.array([0.0, 10.0, -10.0]))
        assert value[0] == pytest.approx(0.5)
        assert value[1] > 0.9999
        assert value[2] < 0.0001

    def test_extent_is_exp_of_log_scale_times_metres(self):
        scale_log = np.array([[0.0, 0.0, 0.0], [-2.0, -1.0, -3.0]])
        extent = splat_cleanup.max_extent_metres(scale_log, 2.0)
        assert extent[0] == pytest.approx(2.0)
        assert extent[1] == pytest.approx(np.exp(-1.0) * 2.0)

    def test_crop_bounds_expand_by_the_margin(self):
        low, high = splat_cleanup.crop_bounds_from_room((0.0, 1.0, 2.0), (3.0, 4.0, 5.0), 0.5)
        assert low == (-0.5, 0.5, 1.5)
        assert high == (3.5, 4.5, 5.5)

    def test_negative_margin_is_rejected(self):
        with pytest.raises(ValueError):
            splat_cleanup.crop_bounds_from_room((0, 0, 0), (1, 1, 1), -0.1)


class TestParams:
    def test_defaults_disable_extent_and_opacity(self):
        params = CleanupParams(bounds_min=(0, 0, 0), bounds_max=(1, 1, 1))
        assert params.max_extent_m == 0.0
        assert params.min_opacity == 0.0

    def test_inverted_bounds_are_rejected(self):
        with pytest.raises(ValueError):
            CleanupParams(bounds_min=(1, 0, 0), bounds_max=(0, 1, 1))

    def test_negative_extent_is_rejected(self):
        with pytest.raises(ValueError):
            CleanupParams(bounds_min=(0, 0, 0), bounds_max=(1, 1, 1), max_extent_m=-1.0)

    def test_opacity_at_one_is_rejected(self):
        with pytest.raises(ValueError):
            CleanupParams(bounds_min=(0, 0, 0), bounds_max=(1, 1, 1), min_opacity=1.0)

    def test_from_room_folds_the_margin_into_the_bounds(self):
        params = CleanupParams.from_room((0, 0, 0), (2, 2, 2), margin_m=0.5, max_extent_m=0.3)
        assert params.bounds_min == (-0.5, -0.5, -0.5)
        assert params.bounds_max == (2.5, 2.5, 2.5)
        assert params.max_extent_m == 0.3


class TestKeepMask:
    def _points(self):
        world = np.array(
            [
                [0.0, 0.0, 0.0],  # inside
                [100.0, 0.0, 0.0],  # far outside
                [0.0, 0.0, 0.0],  # inside but giant
                [0.0, 0.0, 0.0],  # inside but faint
            ]
        )
        opacity = np.array([0.9, 0.9, 0.9, 0.001])
        extent = np.array([0.05, 0.05, 5.0, 0.05])
        return world, opacity, extent

    def test_bounds_only_removes_far_splats(self):
        params = CleanupParams(bounds_min=(-1, -1, -1), bounds_max=(1, 1, 1))
        keep, removed = compute_keep_mask(*self._points(), params)
        assert keep.tolist() == [True, False, True, True]
        assert removed == {"bounds": 1, "extent": 0, "opacity": 0}

    def test_extent_stage_removes_giants_inside_the_box(self):
        params = CleanupParams(
            bounds_min=(-1, -1, -1), bounds_max=(1, 1, 1), max_extent_m=0.3
        )
        keep, removed = compute_keep_mask(*self._points(), params)
        assert keep.tolist() == [True, False, False, True]
        assert removed == {"bounds": 1, "extent": 1, "opacity": 0}

    def test_opacity_stage_removes_faint_splats(self):
        params = CleanupParams(
            bounds_min=(-1, -1, -1), bounds_max=(1, 1, 1), min_opacity=0.5
        )
        keep, removed = compute_keep_mask(*self._points(), params)
        assert keep.tolist() == [True, False, True, False]
        assert removed == {"bounds": 1, "extent": 0, "opacity": 1}

    def test_stage_counts_are_disjoint_and_sum_to_removed(self):
        params = CleanupParams(
            bounds_min=(-1, -1, -1),
            bounds_max=(1, 1, 1),
            max_extent_m=0.3,
            min_opacity=0.5,
        )
        keep, removed = compute_keep_mask(*self._points(), params)
        assert sum(removed.values()) == 4 - int(keep.sum())

    def test_shape_mismatch_is_rejected(self):
        params = CleanupParams(bounds_min=(-1, -1, -1), bounds_max=(1, 1, 1))
        with pytest.raises(ValueError):
            compute_keep_mask(np.zeros((3, 3)), np.zeros(2), np.zeros(3), params)
        with pytest.raises(ValueError):
            compute_keep_mask(np.zeros((3, 2)), np.zeros(3), np.zeros(3), params)


class TestPlySubset:
    def test_read_write_keeps_property_layout_and_changes_only_count(self, tmp_path):
        rows = [
            {"x": 1.0, "y": 2.0, "z": 3.0, "opacity": 5.0, "scale_0": -4.0},
            {"x": 4.0, "y": 5.0, "z": 6.0, "opacity": 6.0, "scale_0": -4.0},
            {"x": 7.0, "y": 8.0, "z": 9.0, "opacity": 7.0, "scale_0": -4.0},
        ]
        source = tmp_path / "source.ply"
        write_ply(source, rows)
        properties, table, header_prefix = clean_splat.read_raw_ply(source)
        assert properties == PROPERTIES
        assert table.shape == (3, len(PROPERTIES))

        keep = np.array([True, False, True])
        output = tmp_path / "subset.ply"
        clean_splat.write_subset_ply(output, header_prefix, table, keep)

        out_properties, out_table, _ = clean_splat.read_raw_ply(output)
        assert out_properties == properties
        assert out_table.shape[0] == 2
        assert out_table[0].tolist() == table[0].tolist()
        assert out_table[1].tolist() == table[2].tolist()

    def test_rebuild_header_replaces_only_the_vertex_line(self):
        prefix = b"ply\nformat binary_little_endian 1.0\nelement vertex 9\nend_header\n"
        rebuilt = clean_splat.rebuild_header(prefix, 4)
        assert rebuilt == b"ply\nformat binary_little_endian 1.0\nelement vertex 4\nend_header\n"


class TestRun:
    def test_filters_a_tiny_ply_against_the_real_contract(self, tmp_path):
        contract = splat_frame.FrameContract.load(MANIFEST)
        mapping = contract.ply_to_world
        centre = np.asarray(contract.splat_bounds.observed_min)
        centre = (centre + np.asarray(contract.splat_bounds.observed_max)) / 2.0
        far = centre + np.array([100.0, 0.0, 0.0])
        # extent 0.05 m -> exp(scale) = 0.05 / m/unit
        small_log = float(np.log(0.05 / mapping.metres_per_unit))
        giant_log = float(np.log(5.0 / mapping.metres_per_unit))

        rows = [
            {"opacity": 10.0, "scale_0": small_log, "scale_1": small_log, "scale_2": small_log},
            {"opacity": 10.0, "scale_0": small_log, "scale_1": small_log, "scale_2": small_log},
            {"opacity": 10.0, "scale_0": giant_log, "scale_1": giant_log, "scale_2": giant_log},
            {"opacity": -10.0, "scale_0": small_log, "scale_1": small_log, "scale_2": small_log},
        ]
        for row, world in zip(rows, (centre, far, centre, centre)):
            raw = raw_for(world, mapping)
            row["x"], row["y"], row["z"] = float(raw[0]), float(raw[1]), float(raw[2])

        source = tmp_path / "tiny.ply"
        write_ply(source, rows)
        out = tmp_path / "tiny_clean.ply"
        report_path = tmp_path / "report.json"
        args = clean_splat.parse_args(
            [
                "--ply", str(source),
                "--manifest", str(MANIFEST),
                "--out", str(out),
                "--report", str(report_path),
                "--margin-m", "0.5",
                "--max-extent-m", "0.30",
            ]
        )
        report = clean_splat.run(args)

        assert report["source"]["splat_count"] == 4
        assert report["output"]["splat_count"] == 2
        assert report["removed"]["per_stage"] == {"bounds": 1, "extent": 1, "opacity": 0}
        assert report["removed"]["total"] == 2
        assert report["source"]["digests"]["md5"] == clean_splat.file_digests(source)["md5"]
        # The report is the reproducibility record: reload it and check it is JSON.
        reloaded = json.loads(report_path.read_text(encoding="utf-8"))
        assert reloaded["params"]["max_extent_m"] == 0.30
        assert len(reloaded["node_translation_world"]) == 3

    def test_min_opacity_stage_runs_when_enabled(self, tmp_path):
        contract = splat_frame.FrameContract.load(MANIFEST)
        mapping = contract.ply_to_world
        centre = (
            np.asarray(contract.splat_bounds.observed_min)
            + np.asarray(contract.splat_bounds.observed_max)
        ) / 2.0
        small_log = float(np.log(0.05 / mapping.metres_per_unit))
        rows = [
            {"opacity": 10.0, "scale_0": small_log, "scale_1": small_log, "scale_2": small_log},
            {"opacity": -10.0, "scale_0": small_log, "scale_1": small_log, "scale_2": small_log},
        ]
        for row in rows:
            raw = raw_for(centre, mapping)
            row["x"], row["y"], row["z"] = float(raw[0]), float(raw[1]), float(raw[2])
        source = tmp_path / "faint.ply"
        write_ply(source, rows)
        args = clean_splat.parse_args(
            [
                "--ply", str(source),
                "--manifest", str(MANIFEST),
                "--out", str(tmp_path / "faint_clean.ply"),
                "--report", str(tmp_path / "faint_report.json"),
                "--min-opacity", "0.5",
            ]
        )
        report = clean_splat.run(args)
        assert report["removed"]["per_stage"]["opacity"] == 1
        assert report["output"]["splat_count"] == 1


class TestNodeTranslation:
    def test_translation_restores_the_source_world_mapping(self):
        contract = splat_frame.FrameContract.load(MANIFEST)
        mapping = contract.ply_to_world
        source_centroid = np.asarray(mapping.origin_ply_units, dtype=np.float64)
        filtered_centroid = source_centroid + np.array([0.3, 0.05, 0.0])
        translation = clean_splat.node_translation_world(filtered_centroid, source_centroid, mapping)

        raw = np.array([1.0, 2.0, 3.0])
        rotation = mapping.rotation()
        expected_world = rotation @ (raw - source_centroid) * mapping.metres_per_unit
        rendered_world = (
            rotation @ (raw - filtered_centroid) * mapping.metres_per_unit + translation
        )
        assert np.allclose(rendered_world, expected_world, atol=1e-12)

    def test_zero_shift_means_zero_translation(self):
        contract = splat_frame.FrameContract.load(MANIFEST)
        mapping = contract.ply_to_world
        source_centroid = np.asarray(mapping.origin_ply_units, dtype=np.float64)
        translation = clean_splat.node_translation_world(source_centroid, source_centroid, mapping)
        assert np.allclose(translation, 0.0)
